modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
issueTrackerURL="https://github.com/progwml6/ironchest/issues"
license="GNU General Public License v3.0"

[[mods]]
    modId="ironchest"
    namespace="ironchest"
    version="${version}"
    displayName="Iron Chests"
    authors="cpw, alexbegt, progwml6"
    description='''
New chests with larger sizes, with in-place upgrade items.
The feature chest is the crystal chest, which is transparent - some inventory contents are visible without opening the chest
    '''
    displayURL="https://minecraft.curseforge.com/projects/iron-chests"

[[dependencies.ironchest]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_min},${forge_version_max})"
    ordering="NONE"
    side="BOTH"
